before_script:
  - yum update -qq &&  yum  install -y -qq golang-googlecode-sqlite-devel-0-0.9.hg74691fb6f837.el7.x86_64 qt5-qtwebchannel-examples-5.9.2-1.el7.x86_64
  - ruby -v
  - which ruby
  - gem install bundler 
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop
`
