# Use default_module_facts.yml for module specific facts.
#
# Facts specified here will override the values provided by rspec-puppet-facts.
---
<<<<<<< HEAD
concat_basedir: "/tmp"
=======
>>>>>>> 358c2d5599e3b70bbdd5e12ad751d558ed2fc6b8
ipaddress: "172.16.254.254"
is_pe: false
macaddress: "AA:AA:AA:AA:AA:AA"
